INSERT INTO makes(make) VALUES('Volvo');
INSERT INTO makes(make) VALUES('Mazda');
INSERT INTO makes(make) VALUES('Honda');
INSERT INTO makes(make) VALUES('Suzuki');
INSERT INTO makes(make) VALUES('Ford');
INSERT INTO makes(make) VALUES('Chevlrolet');
INSERT INTO makes(make) VALUES('Saab');
INSERT INTO makes(make) VALUES('Simca');
INSERT INTO makes(make) VALUES('Dodge');
